version: '3.8'

services:

  server1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    networks:
      - nginx-network
  
  server2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    networks:
      - nginx-network
  
  server3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    networks:
      - nginx-network

  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
    networks:
      - nginx-network
    depends_on:
      - server1
      - server2
      - server3

networks:
  nginx-network:
    driver: bridge