name: Build and Push Docker Image

on:
  push:
    branches: [ master ] # Run on pushes to main branch
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v ./...

    - name: Build the Docker image
      run: docker build ./backend --file ./backend/Dockerfile --tag nginx-go:$(date +%s)

    - name: Push the Docker image
      run: docker push nginx-go:$(date +%s)

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
