name: Build and Push Docker Image

on:
  push:
    branches: [ master ] # Run on pushes to main branch
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./backend --file ./backend/Dockerfile --tag nginx-go:$(date +%s)

